image: mwienk/docker-lftp:latest

stages:
  - deploy

deploy:
  stage: deploy
    # 该命令指定只有 master 分支才能够执行当前任务
    # 部署脚本，在下面的代码中，我用到了很多类似 ${AMAZON_PEM} 的变量，由于我们的私钥、Ip 都算是不宜公开显示的信息，
    # 所以我用到了 Gitlab 的变量工具，在 repo 的 Setting > CI/CD > Secret variables 中，这些变量值只有项目管理员才有权限访问
    # 设置 chmod 权限
    # scp 执行文件拷贝的操作
    # -o ssh_option： 如果习惯于使用ssh_config(5)中的参数传递方式
    # -i identity_file： 从指定文件中读取传输时使用的密钥文件，此参数直接传递给ssh。
  # -r： 递归复制整个目录。

  script:
    # 指定目录覆盖上传 (强制更新)
      - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST -p $port;mirror -RLv ./public /gmlh97ux/wwwroot --ignore-time --transfer-all --parallel=50 --exclude-glob .git* --exclude .git/"
  tags:
    # runner 容器标签
    - docker

  only:
    # 仅 master 分支
    - master

